version: '3.1'

services:
  web:
    image: php:7.4-apache
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: bugs
      MYSQL_USER: bram
      MYSQL_PASSWORD: 123
    volumes:
      - db_data_portfolio:/var/lib/mysql

volumes:
  db_data_portfolio:
