version: '3.1'

services:
  web:
    image: php:7.4-apache
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: bugs
    volumes:
      - db_data_portfolio:/var/lib/mysql:Z

volumes:
  db_data_portfolio:
