version: '3.1'

services:
  web:
    image: php:8.1-apache
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - custom_db  # Renamed db service to custom_db

  custom_db:  # Renamed db service to custom_db
    build:
      context: .
      dockerfile: database.Dockerfile  # Use your specific Dockerfile name
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: bugs
    volumes:
      - ./db-data:/var/lib/mysql
