version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: apache2.Dockerfile
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - custom_db

  custom_db:
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: bugs
    volumes:
      - ./db-data:/var/lib/mysql
