version: '3.1'

services:
  web:
    image: php:7.4-apache
    ports:
      - "85:80"
    volumes:
      - .app/www/public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: portfolio
      MYSQL_USER: bram
      MYSQL_PASSWORD: password123
    volumes:
      - db_data2:/var/lib/mysql

volumes:
  db_data:
